In [21]:
import pandas as pd

data = pd.read_csv("/kaggle/input/startup-logistic-regression/50_Startups.csv")
data.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [22]:
train = data.drop(["Profit", "State"], axis=1)
test = data["Profit"]

from sklearn.model_selection import train_test_split

train_x, test_x, train_y, test_y = train_test_split(train, test, test_size=0.2, random_state=42)
train_x

    R&D Spend  Administration  Marketing Spend
12   93863.75       127320.38        249839.44
4   142107.34        91391.77        366168.42
37   44069.95        51283.14        197029.42
8   120542.52       148718.95        311613.29
3   144372.41       118671.85        383199.62
6   134615.46       147198.87        127716.82
41   27892.92        84710.77        164470.71
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
15  114523.61       122616.84        261776.23
9   123334.88       108679.17        304981.62
16   78013.11       121597.55        264346.06
24   77044.01        99281.34        140574.81
34   46426.07       157693.92        210797.67
31   61136.38       152701.92         88218.23
0   165349.20       136897.80        471784.10
44   22177.74       154806.14         28334.72
27   72107.60       127864.55        353183.81
33   55493.95       103057.49        214634.81
5   131876.90        99814.71        362861.36
29   65605.48       153032.06        107138.38
11  100671.96        91790.61        249744.55
36   28663.76       127056.21        201126.82
1   162597.70       151377.59        443898.53
21   78389.47       153773.43        299737.29
2   153441.51       101145.55        407934.54
43   15505.73       127382.30         35534.17
35   46014.02        85047.44        205517.64
23   67532.53       105751.03        304768.73
40   28754.33       118546.05        172795.67
10  101913.08       110594.11        229160.95
22   73994.56       122782.75        303319.26
18   91749.16       114175.79        294919.57
49       0.00       116983.80         45173.06
20   76253.86       113867.30        298664.47
7   130298.13       145530.06        323876.68
42   23640.93        96189.63        148001.11
14  119943.24       156547.42        256512.92
28   66051.52       182645.56        118148.20
38   20229.59        65947.93        185265.10

In [23]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(train_x, train_y)
pred_y = model.predict(test_x)
pred_y

array([126703.02716461,  84894.75081556,  98893.41815974,  46501.70815036,
       129128.39734381,  50992.69486261, 109016.5536578 , 100878.4641454 ,
        97700.59638629, 113106.15292226])

In [24]:
from sklearn.metrics import mean_absolute_error

error = mean_absolute_error(test_y, pred_y)
print("Mean Absolute Error: ", error)

Mean Absolute Error:  6979.152252370399